mynewsproject/mynewsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls, name='unique_admin'),
    path('', include('mynewsapp.urls')),  # Включаем URL-пути из вашего приложения
    path('users/', include('usersapp.urls', namespace='unique_users')),
    path('api-auth/', include('rest_framework.urls', namespace='unique_rest_framework')),
    path('posts/', include('rest_framework.urls', namespace='unique_posts')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # Обслуживание медиа-файлов в режиме разработки
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mynewsproject/usersapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView





app_name = 'usersapp'


urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
    path('update-token-ajax/', views.update_token_ajax),

]

mynewsproject/usersapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class BlogUser(AbstractUser):
    email = models.EmailField(unique=True)
    is_author = models.BooleanField(default=False)

    # Переопределение метода save
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        # Создаем профиль
        # Если провиль не создан
        if not Profile.objects.filter(user=self).exists():
            Profile.objects.create(user=self)

class Profile(models.Model):
    # При создании пользователя создать Profile
    info = models.TextField(blank=True)
    user = models.OneToOneField(BlogUser, on_delete=models.CASCADE)


#@receiver(post_save, sender=BlogUser)
#def create_profile(sender, instance, **kwargs):
    #print('Сработал обработчик сигнала')
    #if not Profile.objects.filter(user=instance).exists():
        #Profile.objects.create(user=instance)

mynewsproject/usersapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import BlogUser


class RegistrationForm(UserCreationForm):
    class Meta:
        model = BlogUser
        fields = ('username', 'password1', 'password2', 'email')

mynewsproject/usersapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy, reverse

from .forms import RegistrationForm
from django.views.generic import CreateView, DetailView
from .models import BlogUser
from rest_framework.authtoken.models import Token
from django.http import JsonResponse


class UserLoginView(LoginView):
    template_name = 'usersapp/login.html'




class UserCreateView(CreateView):
    model = BlogUser
    template_name = 'usersapp/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('users:login')


class UserDetailView(DetailView):
    template_name = 'usersapp/profile.html'
    model = BlogUser


def update_token(request):
    user = request.user
    # если уже есть
    if user.auth_token:
        # обновить
        user.auth_token.delete()
        Token.objects.create(user=user)
    else:
        # создать
        Token.objects.create(user=user)
    return HttpResponseRedirect(reverse('users:profile', kwargs={'pk': user.pk}))

def update_token_ajax(request):
    user = request.user
    # если уже есть
    if user.auth_token:
        # обновить
        user.auth_token.delete()
        token = Token.objects.create(user=user)
    else:
        # создать
        token = Token.objects.create(user=user)
    return JsonResponse({'key': token.key})

mynewsproject/usersapp/templates/usersapp/login.html
{% extends "base.html" %}

{% block title %}Главная страница{% endblock %}

{% load static %}

{% block content %}
    <!-- Шапка страницы-->
    <header class="masthead" style="background-image: url('{% static 'assets/img/haker.jpg' %}'); background-size: cover;">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Вход</h1>
                        <span class="subheading" style="font-size: 30px;">На сайт</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" class="card p-4">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">Войти</button>
            </form>
            <p class="mt-3">Не выходили еще? <a href="{% url 'users:logout' %}">Выйти</a></p>
        </div>
    </div>
</div>
{% endblock %}

mynewsproject/usersapp/templates/usersapp/profile.html
{% extends "base.html" %}

{% block title %}
Профиль
{% endblock %}

{% block content %}
    Профиль пользователя {{object.username}}
    <hr>
    Токен:
<span id="token">{% if object.auth_token %} {{object.auth_token}} {% else %} не создан {% endif %}</span>
    <form action="{% url 'users:update_token' %}">
        <button type="submit" class="btn btn-primary">Refresh token</button>
    </form>
    <hr>
    <button type="button" id="ajax-btn" class="btn btn-info">Refresh token ajax</button>



{% endblock %}

mynewsproject/usersapp/templates/usersapp/register.html
{% extends "base.html" %}

{% block title %}Главная страница{% endblock %}

{% load static %}

{% block content %}
    <!-- Шапка страницы-->
    <header class="masthead" style="background-image: url('{% static 'assets/img/haker.jpg' %}'); background-size: cover;">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>Регистрация</h1>
                        <span class="subheading" style="font-size: 30px;">На сайте</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form method="post" class="card p-4">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary mt-3">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}