mynewsproject/mynewsapp/urls.py
from django.urls import path, include
from .views import IndexView, AllNewsView, ContactView, create_post_view, SimpleMainAjax
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from .api_views import AllNewsViewSet, PostViewSet, ContactMessageListCreateView
from mynewsapp import views

#router = DefaultRouter()
#router.register(r'allnews', AllNewsViewSet, basename='allnews')

#router = DefaultRouter()
#router.register(r'posts', PostViewSet, basename='posts')

router = DefaultRouter()
router.register(r'allnews', AllNewsViewSet, basename='allnews')
router.register(r'posts', PostViewSet, basename='posts')
router.register(r'contact', ContactMessageListCreateView, basename='contact')


urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # Главная страница
    path('all_news/<int:id>/', AllNewsView.as_view(), name='all_news'),  # Страница с новостями
    path('users/', include('usersapp.urls', namespace='users')),
    path('contact/', ContactView.as_view(), name='contact'),
    path('create/', create_post_view, name='create'),
    path('api/v0/', include(router.urls)),
    path('simple/', views.SimpleMainAjax.as_view(), name='simple_ajax'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mynewsproject/mynewsproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls, name='unique_admin'),
    path('', include('mynewsapp.urls')),  # Включаем URL-пути из вашего приложения
    path('users/', include('usersapp.urls', namespace='unique_users')),
    path('api-auth/', include('rest_framework.urls', namespace='unique_rest_framework')),
    path('posts/', include('rest_framework.urls', namespace='unique_posts')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # Обслуживание медиа-файлов в режиме разработки
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mynewsproject/usersapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView





app_name = 'usersapp'


urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('profile/<int:pk>/', views.UserDetailView.as_view(), name='profile'),
    path('updatetoken/', views.update_token, name='update_token'),
    path('update-token-ajax/', views.update_token_ajax),

]

mynewsproject/mynewsapp/models.py
# mynewsproject/mynewsapp/models.py
from django.db import models
from usersapp.models import BlogUser

class ActiveManager(models.Manager):
    def get_queryset(self):
        all_objects = super().get_queryset()
        return all_objects.filter(is_active=True)

    class Meta:
        abstract = True

class BaseModel(models.Model):
    title = models.CharField(max_length=200)
    link = models.URLField(null=True, blank=True)
    time = models.DateTimeField(auto_now_add=True)
    image_url = models.URLField(null=True, blank=True)
    image = models.ImageField(upload_to='index', null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    user = models.ForeignKey(BlogUser, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=False)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

class AllNews(BaseModel):
    objects = models.Manager()
    active_objects = ActiveManager()

    def has_image(self):
        return self.image is not None

    def some_method(self):
        return 'hello from method'

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

class ContactMessage(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name

mynewsproject/mynewsapp/forms.py
from django import forms
from .models import AllNews


class ContactForm(forms.Form):
    name = forms.CharField(label='Название')
    email = forms.EmailField(label='email')
    message = forms.CharField(label='Сообщение')


class PostForm(forms.ModelForm):
    title = forms.CharField(label='Заголовок', widget=forms.TextInput(attrs={'placeholder': 'Введите заголовок'}))
    link = forms.URLField(label='Ссылка', required=False)
    image_url = forms.URLField(label='Ссылка на изображение', required=False)
    image = forms.ImageField(label='Изображение', required=False)
    content = forms.CharField(label='Содержание', widget=forms.Textarea(attrs={'placeholder': 'Введите содержание'}))

    class Meta:
        model = AllNews
        exclude = ('user',)

mynewsproject/mynewsapp/views.py
# views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.views import View
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import AllNews
from .forms import ContactForm, PostForm
from django.views.generic.detail import DetailView
from django.views.generic import TemplateView


class IndexView(View):
    template_name = 'mynewsapp/index.html'

    def get(self, request):
        posts = AllNews.objects.all()  # Здесь вы должны получить свои объекты постов
        return render(request, self.template_name, {'posts': posts})

class AllNewsView(LoginRequiredMixin, DetailView):
    template_name = 'mynewsapp/all_news.html'
    paginate_by = 5

    def get(self, request, id):
        #all_news_list = AllNews.objects.filter(is_active=True)
        #all_news_list = AllNews.objects.all().order_by('-time')
        #all_news_list = AllNews.active_objects.all()
        all_news_list = AllNews.objects.select_related('user').only('id', 'title', 'time', 'image', 'content',
                                                                    'user__username').all()
        paginator = Paginator(all_news_list, self.paginate_by)
        page = request.GET.get('page')
        try:
            all_news = paginator.page(page)
        except PageNotAnInteger:
            all_news = paginator.page(1)
        except EmptyPage:
            all_news = paginator.page(paginator.num_pages)

        # Изменим запрос, чтобы выбирать только необходимое количество новостей
        all_news_for_page = AllNews.objects.select_related('user').order_by('-time')[:5]

        post = get_object_or_404(AllNews, id=id)

        title = 'главная страница'
        # title = title.capitalize()
        #joke = 'Сайт создан с мною...2023'
        return render(request, self.template_name, {'post': post,
                                                    'all_news_list': all_news,
                                                    'image_present': post.image or post.image_url,
                                                    'all_news_for_page': all_news_for_page})  # 'joke': joke


class ContactView(LoginRequiredMixin, View):
    template_name = 'mynewsapp/contact.html'

    def get(self, request):
        form = ContactForm()
        return render(request, self.template_name, context={'form': form})

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']

            try:
                send_mail(
                    'Contact message',
                    f'Ваше сообщение: {message} принято',
                    'from@example.com',
                    ['viper101011@gmail.com'],
                    fail_silently=False,
                )
                return redirect('index')
            except Exception as e:
                # Логирование ошибки или добавление сообщения об ошибке
                print(f"Error sending email: {e}")
                return redirect('index')
        else:
            return render(request, self.template_name, context={'form': form})

@login_required
def create_post_view(request):
    template_name = 'mynewsapp/create.html'
    if request.method == 'POST':
        form = PostForm(request.POST, files=request.FILES)
        if form.is_valid():
            try:
                form.instance.user = request.user
                form.save()
                return redirect(reverse('index'))
            except Exception as e:
                # Логирование ошибки или добавление сообщения об ошибке
                print(f"Error saving post: {e}")
    else:
        form = PostForm()
    return render(request, template_name, context={'form': form})

class SimpleMainAjax(TemplateView):
    template_name = 'mynewsapp/simple.html'

mynewsproject/mynewsapp/templates/base_templates/base.html
{% load static %}
{% load str_extensions %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Применение фильтра capitalize -->
    <title>{% block title %}{{ "главная страница"|capitalize_first_letter }}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Основные стили CSS (включая Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
    <!-- Навигация-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'index' %}">{{"Главная"|superoutput}}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Меню
                <i class="fas fa-bars"></i>
            </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'contact' %}">Контакты</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'create' %}">Создать пост</a></li>
                        {% if user.is_authenticated %}
                           <li class="nav-item">
                               <span class="red-text" style="font-weight: bold; color: green;">
                                   Привет,<a href="{% url 'usersapp:profile' pk=user.pk %}">{{ user.username|superoutput }}</a>
                               </span>
                           </li>
                            <li class="nav-item">
                                <form method="post" action="{% url 'users:logout' %}">
                                    {% csrf_token %}
                                    <button type="submit" class="nav-link px-lg-3 py-3 py-lg-4" style="border: 1px solid #ccc; background-color: #eee; cursor: pointer; padding: 10px 20px; text-decoration: none; color: #333;">>Выйти</button>
                                </form>
                            </li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:login' %}">Вход</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'users:register' %}">Регистрация</a></li>
                        {% endif %}
                    <!-- Добавьте элементы навигации здесь, если нужно -->
                    </ul>
                </div>
        </div>
    </nav>
    {% block content %}{% endblock %}
     <!-- Подвал-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://twitter.com/?lang=ru">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">
                        <button type="button" id="btn-joke" class="btn btn-info">
                            {{ joke }}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Основной JS библиотеки Bootstrap-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Подключение jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>








    <!-- JS для сайта-->
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/my.js' %}"></script>


</body>
</html>